<?php 
    $code = $block->escapeHtml($block->getMethodCode());
    $method = $block->getMethod();
    $configProvider = $method->getConfig();
?>

<fieldset class="admin__fieldset payment-method" id="payment_form_<?php /* @noEscape */ echo $code; ?>" style="display:none;">
    <br/>
    <div id="apruveDiv" style="display: inline-block; position: relative; margin-top: -3px; margin-left: 7px;"></div>
    <input id="apruve-order-id" name="payment[apruve_order_id]" type="hidden" value="0" />
    <script>
    	delete apruve;
    	delete config;

        var config = <?php echo $configProvider->getConfigJson() ?>;
        require(['Apruve_Payment/js/view/payment/apruve'],function(apruve){
            apruve.initialize();
        });
    </script>
</fieldset>